### ISSUE TITLE
KeyError pixel?

### ISSUE THREAD

**Issue by jstitlow** [macronucleus/chromagnon#21]
Any ideas?

(chromagnon) bioc1301@mprocessor1:~/data/20190710_CaMKIIYFP_YFP647ATTO_MB112c_myrSNAP_JF546SNAP_viol/image$ chromagnon 100719_CaMKIIYFP_YFP647ATTO_MB112c_myrSNAP_JF546SNAP_viol_1h_p1l_heel.tif -R ../cal/100719_CaMKIIYFP_YFP647ATTO_MB112c_myrSNAP_JF546SNAP_viol_1h_p1l_heel.tif -E dv
 * couldn't load module(s):    P
/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/Chromagnon/imgio/bioformatsIO.py:92: UserWarning: Traceback (most recent call last):
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/Chromagnon/imgio/bioformatsIO.py", line 23, in <module>
    import bioformats # reading bioformats is necessary to know if JDK is required or not (in __init__)
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/bioformats/__init__.py", line 19, in <module>
    import javabridge
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/javabridge/jutil.py", line 155, in <module>
    import javabridge._javabridge as _javabridge
ImportError: libjvm.so: cannot open shared object file: No such file or directory

  warnings.warn(errs, UserWarning)
Traceback (most recent call last):
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/bin/chromagnon", line 11, in <module>
    load_entry_point('Chromagnon==0.81', 'console_scripts', 'chromagnon')()
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/Chromagnon/chromagnon.py", line 642, in command_line
    h = imgio.Reader(fn)
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/Chromagnon/imgio/__init__.py", line 35, in Reader
    return _switch(fn, read=True, *args, **kwds)
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/Chromagnon/imgio/__init__.py", line 98, in _switch
    return klasses['tif'](fn, *args, **kwds)
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/Chromagnon/imgio/multitifIO.py", line 29, in __init__
    generalIO.GeneralReader.__init__(self, fn)
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/Chromagnon/imgio/generalIO.py", line 41, in __init__
    self.openFile()
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/Chromagnon/imgio/multitifIO.py", line 38, in openFile
    self.readHeader()
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/Chromagnon/imgio/multitifIO.py", line 41, in readHeader
    self.readMetaData()
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/Chromagnon/imgio/multitifIO.py", line 184, in readMetaData
    pz = _convertUnit(pz, unit)
  File "/usr/people/bioc1301/miniconda3/envs/chromagnon/lib/python2.7/site-packages/Chromagnon/imgio/multitifIO.py", line 21, in _convertUnit
    factor = factors[fromwhat] - factors[towhat] or 0
KeyError: 'pixel'

**Comment by jstitlow** [comment]
Sorry, this was a file format issue caused by loss of metadata during image pre-processing.
