### ISSUE TITLE
arrayIO missing?

### ISSUE THREAD

**Issue by tschoonj** [macronucleus/chromagnon#28]
Hi,

I am trying to create a conda package out of Chromagnon, but I keep running into trouble with `arrayIO`, which appears to be missing?

I keep seeing errors like:

```
$ chromagnon
 * couldn't load module(s):    P
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/bin/chromagnon", line 6, in <module>
    from Chromagnon.chromagnon import command_line
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/Chromagnon/__init__.py", line 12, in <module>
    from . import version, cutoutAlign, alignfuncs, chromformat, aligner, threads, chromagnon
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/Chromagnon/alignfuncs.py", line 7, in <module>
    from Chromagnon import imgio
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/Chromagnon/imgio/__init__.py", line 8, in <module>
    from . import generalIO, mrcIO, imgSeqIO, multitifIO, bioformatsIO, arrayIO
ImportError: cannot import name 'arrayIO' from partially initialized module 'Chromagnon.imgio' (most likely due to a circular import) (/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/Chromagnon/imgio/__init__.py)
```

Any thoughts?

Thanks!

**Comment by macronucleus** [comment]
I am sorry for getting this error. This is because I did not update `setup.py` for long time.
I have updated `setup.py` and some files in `imgio`.
Please try `v0.90`.
If this version did not work for you, please feel free to post here again.
