### ISSUE TITLE
import error after installing Chromagnon

### ISSUE THREAD

**Issue by laithanh77** [macronucleus/chromagnon#29]
I am using conda 4.10.3 with python 3.8.12 on Ubuntu 21.04

My install syntax:

```
python setup.py install
```

My error:

```python
>>> import Chromagnon
 * couldn't load module(s):    P
Traceback (most recent call last):
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/alignfuncs.py", line 6, in <module>
    from Priithon.all import U, F
ModuleNotFoundError: No module named 'Priithon'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/imgio/mrcIO.py", line 8, in <module>
    from . import generalIO, Mrc
ImportError: cannot import name 'Mrc' from partially initialized module 'Chromagnon.imgio' (most likely due to a circular import) (/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/imgio/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/imgio/__init__.py", line 12, in <module>
    from . import generalIO, mrcIO, imgIO, imgSeqIO, multitifIO, bioformatsIO, arrayIO
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/imgio/mrcIO.py", line 10, in <module>
    import generalIO, Mrc
ModuleNotFoundError: No module named 'generalIO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/__init__.py", line 13, in <module>
    from . import version, cutoutAlign, alignfuncs, chromformat, aligner, threads, chromagnon
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/alignfuncs.py", line 18, in <module>
    from Chromagnon import imgio
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/imgio/__init__.py", line 14, in <module>
    from imgio import generalIO, mrcIO, imgIO, imgSeqIO, multitifIO, bioformatsIO, arrayIO
ModuleNotFoundError: No module named 'imgio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/alignfuncs.py", line 6, in <module>
    from Priithon.all import U, F
ModuleNotFoundError: No module named 'Priithon'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/imgio/mrcIO.py", line 8, in <module>
    from . import generalIO, Mrc
ImportError: cannot import name 'Mrc' from partially initialized module 'Chromagnon.imgio' (most likely due to a circular import) (/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/imgio/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/imgio/__init__.py", line 12, in <module>
    from . import generalIO, mrcIO, imgIO, imgSeqIO, multitifIO, bioformatsIO, arrayIO
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/imgio/mrcIO.py", line 10, in <module>
    import generalIO, Mrc
ModuleNotFoundError: No module named 'generalIO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/__init__.py", line 16, in <module>
    from Chromagnon import version, cutoutAlign, alignfuncs, chromformat, aligner, threads, chromagnon
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/alignfuncs.py", line 18, in <module>
    from Chromagnon import imgio
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/imgio/__init__.py", line 14, in <module>
    from imgio import generalIO, mrcIO, imgIO, imgSeqIO, multitifIO, bioformatsIO, arrayIO
ModuleNotFoundError: No module named 'imgio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/__init__.py", line 18, in <module>
    import version, cutoutAlign, alignfuncs, chromformat, aligner, threads, chromagnon
ModuleNotFoundError: No module named 'version'
```

Thanks

**Comment by macronucleus** [comment]
Thank you for raising the issue.
I forgot to add necessary files to git.
I updated the git repository and source code in the release (tag v0.91, note that binary files are still v0.90).
Please try again. Thanks.

**Comment by laithanh77** [comment]
Hi,

I get this error:

```python
>>> import Chromagnon
 * couldn't load module(s):    P
/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/imgio/bioformatsIO.py:93: UserWarning: Traceback (most recent call last):
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/alignfuncs.py", line 6, in <module>
    from Priithon.all import U, F
ModuleNotFoundError: No module named 'Priithon'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/imgio/bioformatsIO.py", line 24, in <module>
    import bioformats # reading bioformats is necessary to know if JDK is required or not (in __init__)
ModuleNotFoundError: No module named 'bioformats'

  warnings.warn(errs, UserWarning)
Traceback (most recent call last):
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/__init__.py", line 13, in <module>
    from . import version, cutoutAlign, alignfuncs, chromformat, aligner, threads, chromagnon
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/chromagnon.py", line 47, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/__init__.py", line 16, in <module>
    from Chromagnon import version, cutoutAlign, alignfuncs, chromformat, aligner, threads, chromagnon
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/chromagnon.py", line 47, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/laithanh/anaconda3/envs/image-stitching/lib/python3.8/site-packages/Chromagnon/__init__.py", line 18, in <module>
    import version, cutoutAlign, alignfuncs, chromformat, aligner, threads, chromagnon
ModuleNotFoundError: No module named 'version'
```

**Comment by macronucleus** [comment]
I fixed the codes that works without wxpython.
Please check the current version (v0.91a). Thanks a lot.
