### ISSUE TITLE
vendorised version of Priithon fails without fftw3

### ISSUE THREAD

**Issue by carandraug** [macronucleus/chromagnon#3]
Priithon seems to have a workaround for the lack of fftw3 module.  However, that workaround seems to be broken:

```
$ python chromagnon/main.py 
Traceback (most recent call last):
  File "chromagnon/main.py", line 47, in <module>
    from PriCommon.ndviewer import main as aui
  File "/home/carandraug/.local/lib/python2.7/site-packages/Chromagnon-0.55-py2.7.egg/PriCommon/ndviewer/__init__.py", line 3, in <module>
    import glfunc, viewerCommon, viewer2, main
  File "/home/carandraug/.local/lib/python2.7/site-packages/Chromagnon-0.55-py2.7.egg/PriCommon/ndviewer/main.py", line 12, in <module>
    from PriCommon import guiFuncs as G ,microscope, bioformatsIO, imgResample
  File "/home/carandraug/.local/lib/python2.7/site-packages/Chromagnon-0.55-py2.7.egg/PriCommon/imgResample.py", line 1, in <module>
    from Priithon.all import U, N
  File "/home/carandraug/.local/lib/python2.7/site-packages/Chromagnon-0.55-py2.7.egg/Priithon/all.py", line 38, in <module>
    import fftfuncs as F
  File "/home/carandraug/.local/lib/python2.7/site-packages/Chromagnon-0.55-py2.7.egg/Priithon/fftfuncs.py", line 11, in <module>
    import fftwam as fftw
  File "/home/carandraug/.local/lib/python2.7/site-packages/Chromagnon-0.55-py2.7.egg/Priithon/fftwam.py", line 97, in <module>
    def rfft(a, nthreads=ncpu):
NameError: name 'ncpu' is not defined
```

**Comment by macronucleus** [comment]
I believe this is fixed in version 0.56.
Thank you.
