### ISSUE TITLE
Error help

### ISSUE THREAD

**Issue by smith6jt-cop** [macronucleus/chromagnon#31]
Hello,
![image](https://github.com/macronucleus/Chromagnon/assets/73438963/a4ff407b-baf3-4d22-b1bf-ba86a242556f)

I have a 3 channel, 3D lightsheet .tiff stack (968x914x1465) as both the reference and target images.  Using 092Win I get the following error:

Traceback (most recent call last):

********************************************
  File "Chromagnon\threads.py", line 206, in run

********************************************
  File "Chromagnon\aligner.py", line 454, in findAlignParamWave

********************************************
  File "Chromagnon\aligner.py", line 418, in setRefImg

********************************************
  File "Chromagnon\alignfuncs.py", line 105, in fixSaturation

********************************************
  File "Chromagnon\alignfuncs.py", line 121, in lowPassGaussFilter

********************************************
  File "Priithon\fftfuncs.py", line 1472, in lowPassGaussFilter

********************************************
  File "Priithon\fftfuncs.py", line 995, in rfft

********************************************
  File "Priithon\fftmanager.py", line 298, in rfft

********************************************
  File "Priithon\fftmanager.py", line 244, in rfft

********************************************
  File "Priithon\fftmanager.py", line 194, in _fftw

********************************************
  File "site-packages\pyfftw\builders\builders.py", line 490, in rfftn

********************************************
  File "site-packages\pyfftw\builders\_utils.py", line 127, in _Xfftn

********************************************
  File "pyfftw\utils.pxi", line 172, in pyfftw.pyfftw.empty_aligned (C:\projects\pyfftw\pyfftw\pyfftw.c:3958)

********************************************
  File "pyfftw\utils.pxi", line 209, in pyfftw.pyfftw.empty_aligned (C:\projects\pyfftw\pyfftw\pyfftw.c:3816)

********************************************
ValueError: cannot reshape array of size 112992228 into shape (1466,914,485)

**Comment by macronucleus** [comment]
Thank you for reporting the problem, and I am so sorry to reply you very late.
The array size in the error message is totally different from the real shape, but I have no idea why.
Probably the error is because the file format is the one that has never been tried for Chromagnon before.
It would be great if you are willing to help us and send your file using this URL. 
https://fexcc.nict.go.jp/user/~th/umt55kodgj8vu0pd1abssvia2c
password: nh84756gE7
If your image file contains important secrets, then it's okay not to send it.
Also, I need to tell you that I may not fix the problem until April due to my current work.
